---

## Install Java

- name: Update APT package manager repositories cache
  become: true
  apt:
    update_cache: yes

- name: Install Java using Ansible
  become: true
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
        - openjdk-11-jdk


## Install Zookeeper

- name: setup group
  group: name={{zookeeper_group}} system=yes

- name: setup user
  user: name={{zookeeper_user}} system=yes group={{zookeeper_group}}

- name: download zookeeper
  get_url:
    url={{zookeeper_download_url}}
    dest={{zookeeper_binary_archive}}
    owner={{zookeeper_user}}
    group={{zookeeper_group}}

- name: uncompress the zookeeper tar
  unarchive:
    src={{zookeeper_binary_archive}}
    dest=/opt
    creates={{zookeeper_binary_dir}}
    copy=no
    owner={{zookeeper_user}}
    group={{zookeeper_group}}

- name: link /opt/zookeeper to the right version
  file:
    src={{zookeeper_binary_dir}}
    path=/opt/zookeeper
    follow=false
    state=link

- name: install zookeeper init script
  template: src=zookeeper-server.j2 dest=/etc/init.d/zookeeper-server mode=0755

- name: add zookeeper binaries to PATH
  copy: src=zookeeper.sh dest=/etc/profile.d/ owner=root group=root mode=644
