---
- include_tasks: stop.yml
  tags: [deploy, restart, stop]
- include_tasks: install.yml
  tags: [deploy]
- include_tasks: configure.yml
  tags: [deploy, configure]
- include_tasks: start.yml
  tags: [deploy, restart]
